services:
  graphdb:
    image: ontotext/graphdb:10.6.3
    container_name: graphdb
    restart: always
    ports:
      - "7200:7200"
    volumes:
      - graphdb-data:/opt/graphdb/home
    environment:
      - GDB_JAVA_OPTS=-Xms1g -Xmx2g -Dgraphdb.workbench.maxUploadSize=500000000

volumes:
  graphdb-data:


